Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2018-05, with the labels that each got.

#134 P3 fix
  p8_integration_tests/test_various/test_synfire_if_curr_exp_x6.py
  spynnaker8/models/recorder.py
  spynnaker8/utilities/neo_convertor.py
Labels: bug

#130 Update integration test for ArrayConnector
  p8_integration_tests/test_array_connector/test_array_connector.py
Labels: bug, enhancement

#139 too big for spin 3
  p8_integration_tests/test_0_1_time_steps/test_overload_system_to_check_recovery/test_read_spike_file_0dot1_time_step.py
Labels: bug

#138 Neo pickle bug skip the tests that fail because of it.
  p8_integration_tests/test_0_1_time_steps/test_gsyn_allow_violate/test_synfire_0dot1_timestep_test_print_gsyn.py
  p8_integration_tests/test_0_1_time_steps/test_malloc_key_allocator/test_synfire_if_curr_exp_with_malloc_key_allocator.py
  p8_integration_tests/test_0_1_time_steps/test_spikes/test_synfire_0dot1_timestep_test_print_spikes.py
  p8_integration_tests/test_0_1_time_steps/test_v/test_synfire_0dot1_timestep_test_print_v.py
  p8_integration_tests/test_0_1_time_steps/test_va_bench_mark_tests/test_va_benchmark.py
  p8_integration_tests/test_1_0_time_steps/test_gsyn/test_synfire_1dot0_timestep_test_print_gsyn.py
  p8_integration_tests/test_1_0_time_steps/test_malloc_key_allocator/test_synfire_if_curr_exp_with_malloc_key_allocator.py
  p8_integration_tests/test_1_0_time_steps/test_spikes/test_synfire_1dot0_timestep_test_print_spikes.py
  p8_integration_tests/test_1_0_time_steps/test_v/test_synfire_1dot0_timestep_test_get_v.py
  p8_integration_tests/test_1_0_time_steps/test_v/test_synfire_1dot0_timestep_test_print_v.py
  p8_integration_tests/test_1_0_time_steps/test_va_bench_mark_tests/test_va_benchmark.py
Labels: wontfix

#142 Test tolerance
  p8_integration_tests/test_array_connector/test_array_connector.py
  p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
  p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py
  p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_no_delay_extension_all_recording.py
  p8_integration_tests/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_no_delays_all_recording.py
  p8_integration_tests/test_report_generation/test_speed_up_report_generation.py
Labels: bug

#127 Missing pynn
  p8_integration_tests/test_selective_recording/test_sampling.py
  p8_integration_tests/test_various/test_stdp_example.py
  spynnaker8/models/data_cache.py
  spynnaker8/models/populations/__init__.py
  spynnaker8/models/populations/idmixin.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_base.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/models/variable_cache.py
  unittests/test_pop_views_assembly/.gitignore
  unittests/test_pop_views_assembly/test_getting.py
  unittests/test_pop_views_assembly/test_idmixin.py
  unittests/test_pop_views_assembly/test_population.py
  unittests/test_pop_views_assembly/test_record.py
  unittests/test_pop_views_assembly/test_views.py
Labels: enhancement

#145 issue solved remove skip
  p8_integration_tests/test_various/spikes_test.py
Labels: bug

#135 Filename/class spelling fix
  unittests/utilities_tests/test_random_ranged.py
Labels: bug

#147 improved handling of cases with zero spikes,
  spynnaker8/models/recorder.py
  spynnaker8/utilities/neo_convertor.py
Labels: bug

#148 Tests a synfire in debug mode
  p8_integration_tests/test_debug_mode/spynnaker.cfg
  p8_integration_tests/test_debug_mode/test_synfire.py
Labels: enhancement
