Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-05, with the labels that each got.

#210 added _ne__ for the dinasours still using python 2.7
  spynnaker8/models/populations/idmixin.py
Labels: bug

#211 eq funtion needs a param
  spynnaker8/models/populations/idmixin.py
Labels: bug

#194 Sdram per timestep
  Jenkinsfile
  Jenkinsfile.cron
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/test_synfire_low_sdram_long_run.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_run/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_run/test_synfire_low_sdram_medium_run.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_run_forever_recorded/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_run_forever_recorded/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_run_forever_recorded/test_run_forever_not_recorded.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_run_forever_recorded/test_run_forever_recorded.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_shorter_run/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_shorter_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_shorter_run/test_spike_source_array.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_shorter_run/test_synfire_low_sdram_low_run.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/too_little_memory/__init__.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/too_little_memory/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/too_little_memory/test_synfire_1_too_low_sdram.py
  p8_integration_tests/quick_test/test_debug_mode/check_debug.py
  p8_integration_tests/quick_test/test_debug_mode/test_java_debug/test_debug.py
  p8_integration_tests/quick_test/test_debug_mode/test_python_debug/test_debug.py
  p8_integration_tests/quick_test/test_spike_source/test_poisson_spike_source.py
  p8_integration_tests/quick_test/test_spike_source/test_spike_source_array.py
  p8_integration_tests/quick_test/test_various/test_multiboard_spike_output.py
  p8_integration_tests/test_auto_pause_and_resume_tests/notes.txt
  p8_integration_tests/test_auto_pause_and_resume_tests/too_little_memory/spynnaker.cfg
  spynnaker8/external_devices/__init__.py
  unittests/test_using_virtual_board/test_from_file_connector.py
  unittests/test_using_virtual_board/test_radial_placer/test_synfire_200n_10pc_2chips_with_no_delays_spike_recording.py
Labels: enhancement

#200 get_time_step should return ms, not microseconds
  spynnaker8/__init__.py
Labels: bug, minor

#199 Add tset function (deprecated, but still in pyNN 0.9 API)
  spynnaker8/models/populations/population.py
Labels: enhancement, minor
