Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-12, with the labels that each got.

#321 Delay in script too large, caught by sPyNNaker fix last week
  unittests/test_integration_using_virtual_board/test_if_curr_alpha.py
Labels: bug

#325 Fix for PyNN changes
  spynnaker8/__init__.py
Labels: BLOCKER!

#320 Make projection.save(...) work for 'all' and 'connections'
  spynnaker8/models/projection.py
Labels: bug, minor

#326 coverage version capped
  Jenkinsfile
Labels: bug
