Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-08, with the labels that each got.

#230 Minor tidying up for fixed number connectors
  p8_integration_tests/quick_test/test_connectors/test_fixed_number_post_connector.py
  p8_integration_tests/quick_test/test_connectors/test_fixed_number_pre_connector.py
  spynnaker8/models/connectors/fixed_number_post_connector.py
  spynnaker8/models/connectors/fixed_number_pre_connector.py
Labels: enhancement

#235 Spike source poisson changes
  p8_integration_tests/quick_test/test_spike_source/test_poisson_spike_source.py
Labels: enhancement

#247 misspelt filename
  Jenkinsfile.cron
  p8_integration_tests/scripts_test/build_script.py
Labels: minor

#246 print on retry
  p8_integration_tests/base_test_case.py
Labels: enhancement, minor

#252 Delete unused files in SpiNNStorageHandlers
  Jenkinsfile
  setup.py
Labels: bug, enhancement
