Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-06, with the labels that each got.

#223 fixed mock to make tests run
  unittests/mocks.py
Labels: bug

#192 Private variables
  spynnaker8/models/data_cache.py
  spynnaker8/models/populations/idmixin.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_base.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_recurrent.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker8/models/variable_cache.py
  spynnaker8/spinnaker.py
  spynnaker8/utilities/log.py
  unittests/test_from_file_connector.py
  unittests/test_pop_views_assembly/test_idmixin.py
  unittests/test_pop_views_assembly/test_views.py
Labels: enhancement

#164 Citation
  CITATION.cff
  MANIFEST.in
  pypi_to_import
  requirements-test.txt
  requirements.txt
  setup.py
  spynnaker8/_version.py
Labels: enhancement

#207 Speed up data in
  .gitignore
  p8_integration_tests/long_test/test_many_boards/test_java_advanced/spynnaker.cfg
  p8_integration_tests/long_test/test_many_boards/test_java_advanced/test_java_advanced.py
  p8_integration_tests/long_test/test_many_boards/test_java_simple/spynnaker.cfg
  p8_integration_tests/long_test/test_many_boards/test_java_simple/test_java_simple.py
  p8_integration_tests/long_test/test_many_boards/test_python_advanced/spynnaker.cfg
  p8_integration_tests/long_test/test_many_boards/test_python_advanced/test_python_advanced.py
  p8_integration_tests/long_test/test_many_boards/test_python_simple/spynnaker.cfg
  p8_integration_tests/long_test/test_many_boards/test_python_simple/test_python_simple.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_shorter_run/test_synfire_low_sdram_low_run.py
  p8_integration_tests/quick_test/test_debug_mode/check_debug.py
  p8_integration_tests/test_from_file_connector/large.connections
  p8_integration_tests/test_from_file_connector/mkconn.py
  p8_integration_tests/test_from_file_connector/test_from_file_connector_large.py
  unittests/test_using_virtual_board/test_examples.py
Labels: enhancement, minor

#228 Make the big connection test run in multiple configurations
  p8_integration_tests/long_test/test_big_connection/__init__.py
  p8_integration_tests/long_test/test_big_connection/test_java_advanced/__init__.py
  p8_integration_tests/long_test/test_big_connection/test_java_advanced/spynnaker.cfg
  p8_integration_tests/long_test/test_big_connection/test_java_advanced/test_big_connection.py
  p8_integration_tests/long_test/test_big_connection/test_java_simple/__init__.py
  p8_integration_tests/long_test/test_big_connection/test_java_simple/spynnaker.cfg
  p8_integration_tests/long_test/test_big_connection/test_java_simple/test_big_connection.py
  p8_integration_tests/long_test/test_big_connection/test_python_advanced/__init__.py
  p8_integration_tests/long_test/test_big_connection/test_python_advanced/spynnaker.cfg
  p8_integration_tests/long_test/test_big_connection/test_python_advanced/test_big_connection.py
  p8_integration_tests/long_test/test_big_connection/test_python_simple/__init__.py
  p8_integration_tests/long_test/test_big_connection/test_python_simple/spynnaker.cfg
  p8_integration_tests/long_test/test_big_connection/test_python_simple/test_big_connection.py
Labels: enhancement, minor

#231 Use labels given to projection in description rather than edge labels
  spynnaker8/models/projection.py
Labels: bug, minor
