Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-03, with the labels that each got.

#150 Move weights and delays
  p8_integration_tests/test_from_file_connector/test_from_file_connector.py
  p8_integration_tests/test_reuse_connector/test_reuse_connector.py
  spynnaker8/models/connectors/fixed_probability_connector.py
  spynnaker8/models/connectors/from_file_connector.py
  spynnaker8/models/connectors/from_list_connector.py
  spynnaker8/models/connectors/small_world_connector.py
  spynnaker8/models/projection.py
  unittests/mocks.py
  unittests/test_from_file_connector.py
Labels: bug

#181 Add integration test for multiple connectors on same edge
  p8_integration_tests/test_population_with_multiple_connectors/test_population_with_multiple_connectors.py
Labels: bug

#149 Test renaming
  unittests/test_integration_using_virtual_board/reset.py
  unittests/test_integration_using_virtual_board/spynnaker.cfg
  unittests/test_integration_using_virtual_board/ssa.py
  unittests/test_integration_using_virtual_board/test.spikes
  unittests/test_integration_using_virtual_board/test_SA_neuron_class_no_edge.py
  unittests/test_integration_using_virtual_board/test_SSP_neuron_class_no_edge.py
  unittests/test_integration_using_virtual_board/test_if_curr_alpha.py
  unittests/test_integration_using_virtual_board/test_one_pop_lif_example.py
  unittests/test_integration_using_virtual_board/test_params_set_as_list.py
  unittests/test_integration_using_virtual_board/test_pynnBrunnelBrianNestSpinnaker.py
  unittests/test_integration_using_virtual_board/test_read_spike_file_1dot0_time_step.py
  unittests/test_integration_using_virtual_board/test_synfire_200n_10pc_2chips_with_no_delays_spike_recording.py
  unittests/test_integration_using_virtual_board/test_synfire_6300n_10pop_10pc_48chips_with_no_delays_spike_recording.py
  unittests/test_integration_using_virtual_board/test_synfire_Izhikevich.py
  unittests/test_integration_using_virtual_board/test_synfire_posson_if_curr_exp_parameter_test_second_none.py
  unittests/test_integration_using_virtual_board/test_tiny.py
  unittests/test_integration_using_virtual_board/test_va_benchmark.py
  unittests/test_using_virtual_board/spynnaker.cfg
  unittests/test_using_virtual_board/test_celltype.py
  unittests/test_using_virtual_board/test_multiple_stdp_mechs_on_same_neuron.py
  unittests/test_using_virtual_board/test_set_record.py
Labels: minor

#195 Deprication wanrings
  p8_integration_tests/test_external_devices/test_recordable_spike_injector.py
  setup.py
Labels: enhancement
