Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-10, with the labels that each got.

#279 test new model templates
  Jenkinsfile
  Jenkinsfile.cron
  p8_integration_tests/test_new_model_templates/test_new_model_templates.py
Labels: enhancement

#287 Pylint
  .pylintrc
  .travis.yml
  Jenkinsfile.cron
  spynnaker8/__init__.py
  spynnaker8/models/connectors/from_list_connector.py
  spynnaker8/models/connectors/small_world_connector.py
  spynnaker8/models/populations/idmixin.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_base.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/setup_pynn.py
  spynnaker8/spinnaker.py
  spynnaker8/spynnaker_plotting.py
  spynnaker8/utilities/exceptions.py
  spynnaker8/utilities/neo_convertor.py
  spynnaker8/utilities/version_util.py
Labels: enhancement, minor

#254 avoid_duplicate_info test
  README.md
  p8_integration_tests/quick_test/test_external_devices/test_recordable_spike_injector.py
  spynnaker8/spinnaker.py
Labels: Jenkins Trigger Only

#274 test compressors
  p8_integration_tests/quick_test/test_onchip_compressor/many_routes.py
  p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/test_mundy_compressor.py
  p8_integration_tests/quick_test/test_onchip_compressor/test_pair/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_pair/test_pair_compressor.py
Labels: enhancement

#283 fixed incorrect import from collections.abc
  p8_integration_tests/quick_test/test_external_devices/test_recordable_spike_injector.py
  setup.py
Labels: bug

#280 Tests for BLOB handling with multiple BLOBs in play
  p8_integration_tests/long_test/test_long_recording/__init__.py
  p8_integration_tests/long_test/test_long_recording/test_java_advanced/__init__.py
  p8_integration_tests/long_test/test_long_recording/test_java_advanced/spynnaker.cfg
  p8_integration_tests/long_test/test_long_recording/test_java_advanced/test_multi_blob_recording.py
  p8_integration_tests/long_test/test_long_recording/test_python_advanced/__init__.py
  p8_integration_tests/long_test/test_long_recording/test_python_advanced/test_multi_blob_recording.py
Labels: enhancement, minor

#263 Fix Poisson Sender
  p8_integration_tests/quick_test/test_external_devices/test_live_neuron_voltage.py
  p8_integration_tests/quick_test/test_spike_source/test_poisson_spike_source.py
  spynnaker8/external_devices/__init__.py
Labels: enhancement

#282 prefix never used so NUKE!
  unittests/mocks.py
Labels: bug

#264 Constants
  Jenkinsfile
  Jenkinsfile.cron
  spynnaker8/models/synapse_dynamics/synapse_dynamics_stdp.py
Labels: enhancement, minor

#270 fixed number of pre on two cores goes boom
  p8_integration_tests/quick_test/test_connectors/test_kernel_connector.py
  p8_integration_tests/quick_test/test_various/test_fixed_number_on_two_cores.py
Labels: bug

#291 annotations on all rather than just some
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_base.py
  spynnaker8/models/populations/population_view.py
Labels: BLOCKER!, enhancement

#271 Fix start message
  spynnaker8/spinnaker.py
Labels: bug

#292 Projections on popviews
  p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  spynnaker8/models/connectors/fixed_probability_connector.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
Labels: BLOCKER!, enhancement

#296 Add "old" sEMD example to NMT tests
  p8_integration_tests/test_new_model_templates/test_new_model_templates.py
Labels: enhancement
