Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-11, with the labels that each got.

#303 Add SSA test with recording and empty lists on cores
  p8_integration_tests/quick_test/test_spike_source/test_spike_source_array.py
Labels: bug

#299 Projections on popviews (again)
  p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  p8_integration_tests/quick_test/test_reuse_connector/test_reuse_connector_different_pops.py
  p8_integration_tests/quick_test/test_various/test_synaptic_expander.py
  spynnaker8/models/connectors/fixed_probability_connector.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  unittests/mocks.py
  unittests/test_from_file_connector.py
Labels: bug

#302 Max cores per chip
  README.md
  p8_integration_tests/quick_test/test_ignores/__init__.py
  p8_integration_tests/quick_test/test_ignores/spynnaker.cfg
  p8_integration_tests/quick_test/test_ignores/test_ignores.py
Labels: enhancement

#300 test for the Chip/ processor / monitor cleanup
  p8_integration_tests/quick_test/test_ignores/__init__.py
  p8_integration_tests/quick_test/test_ignores/spynnaker.cfg
  p8_integration_tests/quick_test/test_ignores/test_ignores.py
  p8_integration_tests/scripts/ignore_script.py
Labels: Jenkins Trigger Only, do not transfer

#304 always allow graph with no vertexes
  p8_integration_tests/quick_test/test_no_vertices_functionality/test_set_to_false/__init__.py
  p8_integration_tests/quick_test/test_no_vertices_functionality/test_set_to_false/spynnaker.cfg
  p8_integration_tests/quick_test/test_no_vertices_functionality/test_set_to_false/test_no_vertices_not_allowed.py
  p8_integration_tests/quick_test/test_no_vertices_functionality/test_set_to_true/spynnaker.cfg
  unittests/test_virtual_board_no_vertices_supported/spynnaker.cfg
Labels: enhancement

#305 Label fix
  p8_integration_tests/quick_test/test_spike_source/test_poisson_spike_source.py
Labels: bug

#312 View recording fix
  spynnaker8/models/populations/idmixin.py
  spynnaker8/models/recorder.py
Labels: bug, enhancement

#314 fixed micro milli double conversion
  spynnaker8/__init__.py
  spynnaker8/spinnaker.py
Labels: bug

#315 moved run message to AbstractSpinnakerBase
  spynnaker8/spinnaker.py
Labels: enhancement
