Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2019-07, with the labels that each got.

#203 Increase number of Java threads
  Jenkinsfile
Labels: enhancement

#206 Logging cleanup
  spynnaker8/models/populations/population.py
Labels: enhancement

#234 Fix save
  p8_integration_tests/quick_test/test_projection_param_retrieval_from_board/test_large_pop_weight_delay_retrieval.py
  spynnaker8/models/projection.py
Labels: bug

#209 Synapse expander on chip kernel connector
  p8_integration_tests/quick_test/test_connectors/test_kernel_connector.py
  spynnaker8/__init__.py
  spynnaker8/models/connectors/__init__.py
  spynnaker8/models/connectors/kernel_connector.py
Labels: enhancement

#232 Better reset support
  p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_set_and_reset.py
  p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_set_toffset.py
  p8_integration_tests/quick_test/test_multi_call_examples/test_multi_extract.py
  p8_integration_tests/quick_test/test_multi_call_examples/test_multi_run.py
  p8_integration_tests/quick_test/test_multi_call_examples/test_reset_initialize.py
  p8_integration_tests/quick_test/test_multi_call_examples/test_stdp_random_run.py
  p8_integration_tests/quick_test/test_synapses/test_synapses_excit_vs_inhib.py
  spynnaker8/spinnaker.py
  unittests/mocks.py
  unittests/test_using_virtual_board/test_one_to_one_connector.py
Labels: bug, enhancement

#237 exclude csa to fix readthedocs
  requirements.txt
  setup.py
Labels: enhancement

#226 Part rig
  unittests/test_using_virtual_board/test_radial_placer/spynnaker.cfg
Labels: enhancement

#242 Delete duplicates of code in SpiNNUtils
  spynnaker8/utilities/log.py
Labels: bug, minor

#239 Turn on test for projection.get() before run that should be fixed now
  p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py
  spynnaker8/external_devices/__init__.py
  unittests/test_using_virtual_board/test_from_file_connector.py
  unittests/test_using_virtual_board/test_from_list_connector.py
Labels: bug
