Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-01, with the labels that each got.

#327 coverage 5.0 is unusable
  .travis.yml
  requirements-test.txt
Labels: BLOCKER!

#338 Update test to use fixed seed to avoid sporadic failures
  p8_integration_tests/quick_test/test_various/test_synaptic_expander.py
Labels: BLOCKER!, bug

#332 Read parameters from machine prior to set
  spynnaker8/models/populations/population.py
Labels: bug

#340 Fix failing microcircuit test
  p8_integration_tests/quick_test/test_grid_based_connectors/test_small_world_connector.py
  p8_integration_tests/scripts_test/test_microcircuit.py
Labels: bug
