Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-02, with the labels that each got.

#337 Remove pynn7 hacks
  requirements.txt
  spynnaker8/spinnaker.py
  spynnaker8/utilities/random_stats/__init__.py
  spynnaker8/utilities/random_stats/random_stats_binomial_impl.py
  spynnaker8/utilities/random_stats/random_stats_exponential_impl.py
  spynnaker8/utilities/random_stats/random_stats_gamma_impl.py
  spynnaker8/utilities/random_stats/random_stats_log_normal_impl.py
  spynnaker8/utilities/random_stats/random_stats_normal_clipped_impl.py
  spynnaker8/utilities/random_stats/random_stats_normal_impl.py
  spynnaker8/utilities/random_stats/random_stats_poisson_impl.py
  spynnaker8/utilities/random_stats/random_stats_randint_impl.py
  spynnaker8/utilities/random_stats/random_stats_scipy_impl.py
  spynnaker8/utilities/random_stats/random_stats_uniform_impl.py
  spynnaker8/utilities/random_stats/random_stats_vonmises_impl.py
  unittests/mocks.py
Labels: enhancement

#351 Reduce skipping
  unittests/test_using_virtual_board/test_from_list_connector.py
  unittests/utilities_tests/test_utility_calls.py
Labels: enhancement

#348 removed hacks to support neo 0.4
  spynnaker8/__init__.py
  spynnaker8/models/recorder.py
  spynnaker8/spynnaker_plotting.py
  spynnaker8/utilities/neo_compare.py
  spynnaker8/utilities/neo_convertor.py
  spynnaker8/utilities/version_util.py
Labels: enhancement

#330 Expose IF_curr_delta as a standard PyNN model
  p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
  spynnaker8/__init__.py
Labels: enhancement

#354 Rename kernel parameters for starts & steps to be less confusing
  p8_integration_tests/quick_test/test_connectors/test_kernel_connector.py
  spynnaker8/models/connectors/kernel_connector.py
Labels: minor

#355 Jenkins fix
  Jenkinsfile
  Jenkinsfile.cron
  p8_integration_tests/base_test_case.py
  p8_integration_tests/quick_test/test_ignores/test_ignores.py
  p8_integration_tests/scripts_test/build_script.py
  p8_integration_tests/scripts_test/script_checker.py
Labels: enhancement

#324 Empty commit for Jenkins
  p8_integration_tests/base_test_case.py
Labels: Jenkins Trigger Only, do not transfer

#357 skip examples which take over 100 seconds
  Jenkinsfile
  p8_integration_tests/scripts_test/build_script.py
Labels: enhancement

#360 Test for large weights bug fix
  p8_integration_tests/quick_test/test_various/test_alltoone_with_large_weight.py
Labels: bug
