Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-10, with the labels that each got.

#471 fixy fixy for andy. you better not be smart now pycharm!
  spynnaker8/models/recorder.py
Labels: BLOCKER!, bug, enhancement, minor

#461 Slice index is not vertex index
  README.md
  unittests/test_from_file_connector.py
Labels: enhancement

#468 No more storage handlers
  .travis.yml
  Jenkinsfile
  Jenkinsfile.cron
  doc/doc_requirements.txt
  doc/source/conf.py
  pypi_to_import
  requirements.txt
  setup.py
Labels: bug, enhancement, minor

#479 failed test
  p8_integration_tests/quick_test/test_master_pop/__init__.py
  p8_integration_tests/quick_test/test_master_pop/algorithms.xml
  p8_integration_tests/quick_test/test_master_pop/key_constraint_adder.py
  p8_integration_tests/quick_test/test_master_pop/spynnaker.cfg
  p8_integration_tests/quick_test/test_master_pop/test_master_pop_merging_with_pop_and_delays_mergable.py
Labels: BLOCKER!, bug

#475 ZoneKeyAllocator fixes
  p8_integration_tests/quick_test/test_routing_info_allocator/test_basic/__init__.py
  p8_integration_tests/quick_test/test_routing_info_allocator/test_basic/spynnaker.cfg
  p8_integration_tests/quick_test/test_routing_info_allocator/test_basic/test_basic_routing_info.py
  p8_integration_tests/quick_test/test_routing_info_allocator/test_zoned/__init__.py
  p8_integration_tests/quick_test/test_routing_info_allocator/test_zoned/spynnaker.cfg
  p8_integration_tests/quick_test/test_routing_info_allocator/test_zoned/test_zoned_routing_info.py
Labels: enhancement
