Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-12, with the labels that each got.

#511 Remove config that shouldn't be required
  p8_integration_tests/quick_test/test_external_devices/spynnaker.cfg
Labels: enhancement

#512 remove AbstractRecordable as it was never used correctly
  p8_integration_tests/quick_test/test_external_devices/spynnaker.cfg
Labels: bug

#273 cherry picked partitioner
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  spynnaker8/models/projection.py
  unittests/test_from_file_connector.py
Labels: enhancement

#515 Changes that hopefully fix Jenkins run
  Jenkinsfile
  Jenkinsfile.cron
Labels: bug

#510 removed unused io functionality
  Jenkinsfile
  README.md
Labels: Jenkins Trigger Only

#520 Convert to use new actions
  .github/workflows/python_actions.yml
  .travis.yml
Labels: enhancement, minor
