Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-08, with the labels that each got.

#431 Testing of remove_gnu_functions
  spynnaker8/models/populations/population.py
Labels: bug

#433 Add testing with Python 3.8
  .travis.yml
  Jenkinsfile
  Jenkinsfile.cron
  setup.py
  spynnaker8/models/populations/population.py
Labels: enhancement, minor

#427 Pre filter
  p8_integration_tests/quick_test/test_iobuf/test_cores_and_binaries_recorded/spynnaker.cfg
  p8_integration_tests/quick_test/test_iobuf/test_only_cores_recorded/spynnaker.cfg
  unittests/test_using_virtual_board/test_radial_placer/spynnaker.cfg
Labels: enhancement

#437 fixes issue from https://github.com/SpiNNakerManchester/sPyNNaker/issues/865
  p8_integration_tests/quick_test/test_additional_params_on_pop_not_recogonised/__init__.py
  p8_integration_tests/quick_test/test_additional_params_on_pop_not_recogonised/test_additional_params_mix.py
  p8_integration_tests/quick_test/test_additional_params_on_pop_not_recogonised/test_additional_params_needed.py
  p8_integration_tests/quick_test/test_additional_params_on_pop_not_recogonised/test_additional_params_not_needed.py
Labels: bug
