Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-11, with the labels that each got.

#485 Add tests for STDP with multiplicative weight dependence
  p8_integration_tests/base_test_case.py
  p8_integration_tests/quick_test/test_stdp/test_STDP_nearest_pair_multiplicative.py
  p8_integration_tests/quick_test/test_stdp/test_STDP_pair_multiplicative.py
Labels: enhancement

#487 Add a test for nearest-pair STDP rule with conductance neuron model
  p8_integration_tests/quick_test/test_stdp/test_IF_cond_exp_stdp_nearest_pair_additive.py
Labels: enhancement

#490 Turn on Python checks
  .github/workflows/python_actions.yml
  .ratexcludes
  p8_integration_tests/scripts_test/build_script.py
  spynnaker8/spynnaker_plotting.py
  spynnaker8/utilities/neo_convertor.py
  unittests/test_using_virtual_board/test_examples.py
  unittests/test_using_virtual_board/test_introlabs.py
Labels: BLOCKER!, enhancement

#493 use gitclone2
  .github/workflows/python_actions.yml
Labels: BLOCKER!, bug

#492 Python actions with sphinx
  .github/workflows/python_actions.yml
  requirements-test.txt
Labels: enhancement

#486 no longer just jenkins. got a method name change
  LICENSE.md
  unittests/test_pop_views_assembly/test_record.py
  unittests/test_using_virtual_board/test_set_record.py
Labels: enhancement

#467 Run synchronized
  p8_integration_tests/quick_test/test_external_devices/test_live_sync.py
  spynnaker8/external_devices/__init__.py
  spynnaker8/spinnaker.py
Labels: enhancement
