Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-05, with the labels that each got.

#391 Fix a lot of minor errors in integration tests
  p8_integration_tests/quick_test/test_change_neuron_parameters_between_runs/test_synfire_poisson_if_curr_exp_parameter_test_second_none.py
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  p8_integration_tests/quick_test/test_connectors/test_kernel_connector.py
  p8_integration_tests/quick_test/test_external_devices/test_recordable_spike_injector.py
  p8_integration_tests/quick_test/test_grid_based_connectors/test_distance_dependent_probability_connector.py
  p8_integration_tests/quick_test/test_grid_based_connectors/test_small_world_connector.py
  p8_integration_tests/quick_test/test_iobuf/test_iobuf_without_during_run_flag/test_noIobuf_during_run.py
  p8_integration_tests/quick_test/test_iobuf/test_none_but_active_recorded/test_no_cores.py
  p8_integration_tests/quick_test/test_no_vertices_functionality/test_set_to_true/test_no_vertices.py
  p8_integration_tests/quick_test/test_selective_recording/test_recording_on_off.py
  p8_integration_tests/quick_test/test_stdp/test_IF_cond_exp_stdp_mad_pair_additive.py
  p8_integration_tests/quick_test/test_stdp/test_STDP_nearest_pair_additive.py
  p8_integration_tests/quick_test/test_stdp/test_STDP_pair_additive.py
  p8_integration_tests/quick_test/test_various/test_tiny_with_reset.py
  p8_integration_tests/test_from_file_connector/test_from_file_connector_large.py
  p8_integration_tests/x_test/test_0_1_time_steps/test_gsyn_allow_violate/test_synfire_0dot1_timestep_test_print_gsyn.py
  p8_integration_tests/x_test/test_buffer_manager/test_if_curr_exp_with_v_recording/test_synfire_if_curr_exp.py
  p8_integration_tests/x_test/test_selective_recording/simple_master.py
  p8_integration_tests/x_test/test_selective_recording/test_sampling.py
  p8_integration_tests/x_test/test_selective_recording/test_thritytwo.py
  p8_integration_tests/x_test/test_various/spikes_test.py
Labels: minor

#405 Fix jenkins
  .travis.yml
  p8_integration_tests/scripts_test/script_checker.py
Labels: BLOCKER!, bug

#406 Test to check connection estimates are working
  p8_integration_tests/quick_test/test_connectors/test_fixed_number_post_connector.py
Labels: bug
