Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-09, with the labels that each got.

#444 Broken setuptools for now
  Jenkinsfile
  Jenkinsfile.cron
Labels: BLOCKER!, bug

#450 Add Link to Info
  p8_integration_tests/quick_test/test_ignores/spynnaker.cfg
Labels: enhancement

#449 Nuke common
  README.md
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_stdp.py
Labels: enhancement

#408 Add a test to check the delay expander works with size(pop1)!=size(pop2)
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  p8_integration_tests/quick_test/test_connectors/test_fixed_number_pre_connector.py
  p8_integration_tests/quick_test/test_various/test_alltoall_with_delay_extension.py
Labels: bug

#454 Log binaries
  Jenkinsfile
  Jenkinsfile.cron
Labels: enhancement

#421 bits for determism
  .gitignore
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_long_run/test_synfire_low_sdram_long_run.py
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_fail_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_auto_pause_and_resume_tests/test_medium_run/spynnaker.cfg
  p8_integration_tests/quick_test/test_spike_source/test_variable_rate.py
  p8_integration_tests/quick_test/test_stdp/test_STDP_pair_additive.py
  p8_integration_tests/scripts_test/build_script.py
  requirements-test.txt
  unittests/test_using_virtual_board/test_set_record.py
Labels: minor

#457 better log and testing the tester
  Jenkinsfile
Labels: minor
