Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2020-03, with the labels that each got.

#347 Add multi-core test for OneToOne when using PopulationViews
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
Labels: enhancement

#365 Clear on reset fix
  p8_integration_tests/quick_test/test_various/test_reset_clears_delayed_spike.py
Labels: bug

#363 donal_fec_changes
  README.md
  p8_integration_tests/quick_test/test_debug_mode/check_debug.py
Labels: Jenkins Trigger Only

#371 skip 2 long examples
  p8_integration_tests/scripts_test/build_script.py
Labels: enhancement

#372 Parallel examples
  Jenkinsfile
  p8_integration_tests/base_test_case.py
  p8_integration_tests/scripts_test/build_script.py
Labels: enhancement

#382 more agggressive cleanup on second setup
  spynnaker8/__init__.py
Labels: enhancement

#383 Jenkins commit
  p8_integration_tests/quick_test/test_struct_pl/test_structural_shared.py
  p8_integration_tests/quick_test/test_struct_pl/test_structural_with_stdp.py
Labels: minor

#384 Power provenance testing
  p8_integration_tests/quick_test/test_power_monitoring/__init__.py
  p8_integration_tests/quick_test/test_power_monitoring/spynnaker.cfg
  p8_integration_tests/quick_test/test_power_monitoring/test_power_mon.py
Labels: enhancement

#385 Add test to check that RandomDistributions work for each possible dist
  p8_integration_tests/quick_test/test_various/test_params_using_random_dists.py
Labels: bug

#333 Make FixedNumberConnectors work with PopulationViews
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
  spynnaker8/models/projection.py
Labels: enhancement

#322 Doc fix
  doc/source/conf.py
  doc/source/index.rst
  doc/source/modules.rst
  spynnaker8/__init__.py
  spynnaker8/external_devices/__init__.py
  spynnaker8/extra_models/__init__.py
  spynnaker8/models/connectors/__init__.py
  spynnaker8/models/connectors/all_to_all_connector.py
  spynnaker8/models/connectors/array_connector.py
  spynnaker8/models/connectors/csa_connector.py
  spynnaker8/models/connectors/distance_dependent_probability_connector.py
  spynnaker8/models/connectors/fixed_number_post_connector.py
  spynnaker8/models/connectors/fixed_number_pre_connector.py
  spynnaker8/models/connectors/fixed_probability_connector.py
  spynnaker8/models/connectors/from_file_connector.py
  spynnaker8/models/connectors/from_list_connector.py
  spynnaker8/models/connectors/index_based_probability_connector.py
  spynnaker8/models/connectors/kernel_connector.py
  spynnaker8/models/connectors/multapse_connector.py
  spynnaker8/models/connectors/one_to_one_connector.py
  spynnaker8/models/connectors/small_world_connector.py
  spynnaker8/models/data_cache.py
  spynnaker8/models/populations/assembly.py
  spynnaker8/models/populations/idmixin.py
  spynnaker8/models/populations/population.py
  spynnaker8/models/populations/population_base.py
  spynnaker8/models/populations/population_view.py
  spynnaker8/models/projection.py
  spynnaker8/models/recorder.py
  spynnaker8/models/synapse_dynamics/__init__.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_stdp.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_static.py
  spynnaker8/models/synapse_dynamics/synapse_dynamics_structural_stdp.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_pfister_spike_triplet.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_recurrent.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_nearest_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_spike_pair.py
  spynnaker8/models/synapse_dynamics/timing_dependence/timing_dependence_vogels_2011.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_additive_triplet.py
  spynnaker8/models/synapse_dynamics/weight_dependence/weight_dependence_multiplicative.py
  spynnaker8/models/variable_cache.py
  spynnaker8/spynnaker8_simulator_interface.py
  spynnaker8/spynnaker_plotting.py
  spynnaker8/utilities/exceptions.py
  spynnaker8/utilities/id.py
  spynnaker8/utilities/neo_compare.py
  spynnaker8/utilities/neo_convertor.py
Labels: enhancement, minor
