Repository SpiNNakerManchester/sPyNNaker8, pull requests merged in 2021-01, with the labels that each got.

#521 upgrade neo
  README.md
  setup.py
Labels: BLOCKER!, bug

#504 Update tests due to seed method changes
  p8_integration_tests/quick_test/test_connectors/test_connectors.py
Labels: bug

#527 remove test for MundyOnChipRouterCompression
  p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/spynnaker.cfg
  p8_integration_tests/quick_test/test_onchip_compressor/test_mundy/test_mundy_compressor.py
Labels: enhancement

#533 jenkins and extra tests!
  unittests/test_pop_views_assembly/test_models.py
Labels: bug, enhancement
